camera:
    camera:
      ros__parameters:
        device_type: 'd405'
        serial_no: ''
        usb_port_id: ''

        color_fps: 30.0
        color_height: 480
        color_width: 848
        #color_qos: "SENSOR_DATA"
        #depth_fps: 30.0
        #depth_height: 720
        #depth_width: 1280
        #depth_qos: "SENSOR_DATA"
        #infra_height: 720
        #infra_width: 1280
        infra_height: 480
        intra_width: 848
        #infra_qos: "SENSOR_DATA"

        enable_color: true
        enable_depth: true
        align_depth: true
        enable_infra1: true
        enable_infra2: true

        stereo_module:
          emitter_enabled: 1

        filters: ''
        #filters: 'disparity,spatial,temporal,decimation'
        enable_pointcloud: false
        pointcloud_texture_index: 0
        pointcloud_texture_stream: RS2_STREAM_COLOR
        rosbag_filename: ''
